apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vehicle-api
  description: vehicle-api
  tags:
  - java
  - spring
  - web
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=vehicle-api'
spec:
  type: service
  lifecycle: experimental
  owner: demo
  providesApis:
  - vehicle-api
